### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [compute-io/cosine-similarity#2]

**Comment by domeccleston** [comment]
Just wrote a Typescript package for that purpose @VladislavSmolyanoy! Check it out if types are a priority :)

https://github.com/domeccleston/cosim

**Comment by VladislavSmolyanoy** [comment]
Awesome, thanks

**Comment by kgryte** [comment]
One word of caution regarding the linked alternative package is that, based on its current implementation, it is likely to have numerical stability issues.

**Comment by domeccleston** [comment]
Interesting, what kind of issues @kgryte?

**Comment by Planeshifter** [comment]
TypeScript annotations have been added per #3. Closing.
